# Generated by go2rpm 1.11.1
%bcond_without check

%global goipath code.tokarch.uk/mainnika/acpi-wakeup-fixxer
%global common_description %{expand:
This package provides a fix for ACPI wakeup issues on MacBookPro12,x.}

%global golicenses      LICENSE
%global godocs          README.md

%global archivename main
%global archiveext  tar.gz
%global topdir      acpi-wakeup-fixxer-main

Name:           golang-code-tokarch-mainnika-acpi-wakeup-fixxer
Version:        0
Release:        0.1%{?dist}
Summary:        None

License:        MIT
URL:            https://code.tokarch.uk/mainnika/acpi-wakeup-fixxer
Source:         https://github.com/mainnika/acpi-wakeup-fixxer/archive/refs/heads/%{archivename}.%{archiveext}

%description %{common_description}

%gometa
%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/acpi-wakeup-fixxer %{goipath}/cmd/acpi-wakeup-fixxer

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
